"""Shared helpers for all command modules (compatibility facade)."""

from __future__ import annotations

import sys
import click
from .. import account as account_service
from ..auth import get_token as auth_get_token
from .common import (
    ConfigProxy,
    _check_token_expiry,
    _client_cache,
    _ctx_account_name,
    _decode_exp,
    _exit_with_error,
    _get_client,
    _handle_api_error,
    _is_json_mode,
    _is_piped,
    _root_context,
    _stdin_is_tty,
    _wants_json,
    account_option,
    cfg,
    confirm_action,
    do_login,
    get_account_name,
    get_category_color_map,
    get_token,
    is_dry_run_mode,
    is_no_input_mode,
    maybe_dry_run,
    resolve_body_input,
    verify_token,
)
from ..client import OutlookClient
from ..formatter import (
    console,
    print_accounts,
    print_attachments,
    print_calendars,
    print_categories,
    print_contacts,
    print_email,
    print_email_raw,
    print_error,
    print_event_detail,
    print_events,
    print_folders,
    print_inbox,
    print_meeting_suggestions,
    print_people,
    print_success,
    print_summary_dashboard,
    print_whoami,
)
from ..serialization import (
    error_json,
    save_json,
    to_json,
    to_json_envelope,
)

__all__ = [
    "ConfigProxy",
    "_check_token_expiry",
    "_client_cache",
    "_ctx_account_name",
    "_exit_with_error",
    "_get_client",
    "_handle_api_error",
    "_is_json_mode",
    "_is_piped",
    "_root_context",
    "_stdin_is_tty",
    "_wants_json",
    "account_option",
    "cfg",
    "confirm_action",
    "console",
    "do_login",
    "error_json",
    "get_account_name",
    "get_category_color_map",
    "get_token",
    "is_dry_run_mode",
    "is_no_input_mode",
    "maybe_dry_run",
    "print_accounts",
    "print_attachments",
    "print_calendars",
    "print_categories",
    "print_contacts",
    "print_email",
    "print_email_raw",
    "print_error",
    "print_event_detail",
    "print_events",
    "print_folders",
    "print_inbox",
    "print_meeting_suggestions",
    "print_people",
    "print_success",
    "print_summary_dashboard",
    "print_whoami",
    "resolve_body_input",
    "save_json",
    "to_json",
    "to_json_envelope",
]
