"""Terminal output formatters using Rich."""

from __future__ import annotations

from .calendar import (
    _attendee_response_icon,
    _attendee_type_suffix,
    _event_time_text,
    _format_recurrence,
    _response_icon,
    print_calendars,
    print_event_detail,
    print_events,
    print_meeting_suggestions,
    print_people,
)
from .helpers import (
    ACTIVE_DOT,
    INACTIVE_DOT,
    OUTLOOK_CATEGORY_COLORS,
    RESPONSE_ICONS,
    _format_date,
    _format_size,
    _html_to_text,
    _safe,
    _table,
    _truncate,
    console,
    print_error,
    print_success,
)
from .mail import (
    _category_text,
    _flag_text,
    print_email,
    print_email_raw,
    print_inbox,
    print_thread,
)
from .misc import (
    _ordered_folders,
    _summary_event_time,
    _unread_badge,
    print_accounts,
    print_attachments,
    print_categories,
    print_contacts,
    print_folders,
    print_summary_dashboard,
    print_whoami,
)

__all__ = [
    "ACTIVE_DOT",
    "INACTIVE_DOT",
    "OUTLOOK_CATEGORY_COLORS",
    "RESPONSE_ICONS",
    "_attendee_response_icon",
    "_attendee_type_suffix",
    "_category_text",
    "_event_time_text",
    "_flag_text",
    "_format_date",
    "_format_recurrence",
    "_format_size",
    "_html_to_text",
    "_ordered_folders",
    "_response_icon",
    "_safe",
    "_summary_event_time",
    "_table",
    "_truncate",
    "_unread_badge",
    "console",
    "print_accounts",
    "print_attachments",
    "print_calendars",
    "print_categories",
    "print_contacts",
    "print_email",
    "print_email_raw",
    "print_error",
    "print_event_detail",
    "print_events",
    "print_folders",
    "print_inbox",
    "print_meeting_suggestions",
    "print_people",
    "print_success",
    "print_summary_dashboard",
    "print_thread",
    "print_whoami",
]
